### PR TITLE
Update mapbox-gl-native to 5.0.0

### PR DESCRIPTION
**Pull request by kjkurtz**

### CODE REVIEW

**Comment by kjkurtz** [comment]
Looks like the tests are failing on travis-ci due to missing MAPBOX_API_TOKEN environment variable. The tests pass locally with the variable set.

**Comment by brendan-ward** [comment]
@kjkurtz thanks for submitting this and for letting me know about the issue with the token.  It looks like it works fine for changesets originating from the main repo, but not from PRs originating from forks of the repo.  Will work on a fix.

**Comment by brendan-ward** [comment]
@kjkurtz I modified the test suite to skip Mapbox tests if the Mapbox token is not present, since it is quite difficult to have a secure Mapbox token on Travis-CI that is used by PRs originating from forks of the repo.

This hopefully makes it easier to feel confident about submitting a PR.  Thanks again for letting me know about the issue!

**Comment by kjkurtz** [comment]
No worries! Happy to help. What is the domain used by Travis-CI to run the tests? Just curious, because generally I'm OK with checking in Mapbox tokens to version control as long as I can secure the domains that are allowed by that token. If it's something like localhost or a generic Travis-CI domain, I can definitely see where that would be difficult!

**Comment by brendan-ward** [comment]
@kjkurtz the token I checked in while testing this was locked to originate from `travis-ci.org`, but that failed with a not authorized response- indicating that wasn't the exact hostname used in the request.

I didn't have a chance to add additional logging to Travis to try and determine the originating hostname; I didn't find anything in the docs.  I didn't feel spectacular about having a token in there anyway, since even though locked to Travis, it could still get picked up and used for tests beyond this repo.  I think skipping tests when the token is not present is a reasonable compromise for now - they at least signal to us that we need to run the tests locally too, but without failing outright and frustrating contributors.

**Pull request merged**
