### PR TITLE
Adds request logging to server

### PR DESCRIPTION
**Pull request by normanrz**
Uses `morgan` to add a basic request logging to the server.

Screenshot 2020-03-27 at 11 36 58

### CODE REVIEW

**Comment by brendan-ward** [comment]
@normanrz thanks for adding this!

For GET requests, this logs the incoming mapbox token.  That doesn't seem like a good idea, esp. if the tokens originate from users of this server rather than the operator of it.

I didn't see an obvious way to exclude certain query parameters from the incoming URL prior to logging.

What do you think about this?

**Comment by normanrz** [comment]
That is a good point. I added code for stripping the query from the log.

**Comment by brendan-ward** [comment]
@normanrz thanks for updating that - though now I wonder if it went too far the other way.  What are your goals for logging?  

Since path does not vary with the request, all this tells us now is when an incoming request is made and how long it took to respond.  Are there particular things we want from the query params / request body (if POST)?

**Comment by normanrz** [comment]
I need logging to see that requests are happening, how long they take and which status code they got. It is useful zo distinguish between render calls and the periodic healthchecks.

**Pull request merged**
